//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Registrate.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Registrate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Afganistán
        ///Albania
        ///Alemania
        ///Andorra
        ///Angola
        ///Antigua y Barbuda
        ///Arabia Saudita
        ///Argelia
        ///Argentina
        ///Armenia
        ///Australia
        ///Austria
        ///Azerbaiyán
        ///Bahamas
        ///Bahréin
        ///Bangladés
        ///Barbados
        ///Bielorrusia
        ///Bélgica
        ///Belice
        ///Benín
        ///Bután
        ///Bolivia
        ///Bosnia-Herzegovina
        ///Botsuana
        ///Brasil
        ///Brunéi
        ///Bulgaria
        ///Burkina Faso
        ///Burundi
        ///Cabo Verde
        ///Camboya
        ///Camerún
        ///Canadá
        ///Chad
        ///República Checa
        ///Chequia
        ///Chile
        ///China
        ///Chipre
        ///Colombia
        ///Comoras
        ///Congo
        ///República Democrática del Congo
        ///Corea del Norte
        ///Corea del Sur
        ///Costa Rica
        ///Co [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string paises {
            get {
                return ResourceManager.GetString("paises", resourceCulture);
            }
        }
    }
}
